language: node_js
node_js:
  - "lts/*"

cache:
  directories:
    - node_modules
before_script:

after_script:
  - cd ./dist

#- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
script:
  - npm run build
install:
  - npm install

branches:
  only:
    - master